# Generated by Django 3.0.1 on 2019-12-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20191219_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='vehicle_type',
            new_name='bicycle_type',
        ),
        migrations.RenameField(
            model_name='bicycle',
            old_name='vehicle_size',
            new_name='frame_material',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='vehicle',
            new_name='bicycle',
        ),
        migrations.RenameField(
            model_name='rentalrate',
            old_name='vehicle_type',
            new_name='bicycle_type',
        ),
        migrations.RenameField(
            model_name='rentalrate',
            old_name='vehicle_size',
            new_name='frame_material',
        ),
    ]
