# Generated by Django 3.0.1 on 2019-12-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20191219_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='rental_rate',
        ),
    ]
