# Generated by Django 3.0.1 on 2019-12-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_bicycle_rental_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='date_created',
            field=models.DateField(),
        ),
    ]
