# Generated by Django 3.0.1 on 2019-12-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_bicycle_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrate',
            name='img_path',
            field=models.CharField(default='/rental/images/canyon.png', max_length=100),
        ),
    ]
